CREATE TABLE IF NOT EXISTS shopping_list(
    item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    item_price decimal(12,2),
    item_date_added TIMESTAMP DEFAULT now() NOT NULL,
    item_checked BOOLEAN DEFAULT 0 NOT NULL,
    category grocery NOT NULL
);

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM(
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

